<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="B2ML39194" ignored="0" name="Validating Using Cucumber" tests="2" failures="2" timestamp="2021-08-30T08:02:18 IST" time="49.973" errors="0">
  <testcase name="feature" time="49.422" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [true] but found [false]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.AssertionError: expected [true] but found [false]
at stepDefinitions.stepDefinition.validate_the_error_message(stepDefinition.java:76)
at âœ½.Then validate the error message(Login.feature:7)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="49.589" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at resources.Screenshot.getScreenshot(Screenshot.java:27)
at resources.Listeners.onTestFailure(Listeners.java:90)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Validating Using Cucumber -->
